### PR TITLE
set device in agent_update

### LINKED ISSUE #87: Possible Bug: Must be transferred to CPU before property collection
Line 33 of data_collection.py

maybe lines 45 and 46 too

I had to do an emergency fix to allow it to run on snellius gpu, it may not be the best.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
closes #87 

see https://github.com/SDCCA/DGL-PTM/issues/87#issuecomment-2276074726

### CODE REVIEW

**Comment by SarahAlidoost** [comment]
@vmgaribay can you please review this pull request by running your experiment on snellius and check if issue #87 has been fixed? Please do not merge this pull request because I asked @vanlankveldthijs also to review the changes.

**Review by vanlankveldthijs — APPROVED** [review]
Implementation looks good.
All tests successful, no new tests needed.

Good job. Can be merged if the snellius experiment is successful too.

**Review by vmgaribay — APPROVED** [review]
Device now defined for update functions, and as a bonus, appears to have been lint-rolled. Should be good to merge

**Comment by vmgaribay** [comment]
Ah, no! Missed a bit of lint.

**Comment by vmgaribay** [comment]
I see, it is the `size` thing that needs to be replaced with `n_samples`.
I wonder if I can change it without ruining it...

nope

**Comment by vmgaribay** [comment]
Yep!

**Comment by SarahAlidoost** [comment]
> I see, it is the `size` thing that needs to be replaced with `n_samples`. I wonder if I can change it without ruining it...
> 
> nope

I guess you missed issue #111 :smile:

**Pull request merged**
