### PR TITLE
added local attachement demo

### PR DESCRIPTION
**Pull request by meiertgrootes**

### CODE REVIEW

**Comment by cpranav93** [comment]
I get the following error:
DGLError: 'meta.yaml' cannot be found under [./toy_dataset/toy_local_attach.

Any idea how it worked for you without meta.yaml in the folder?

**Comment by meiertgrootes** [comment]
Sorry, missed some files when migrating from PovertyTrap. should work now

**Comment by cpranav93** [comment]
It looks great and quite elegant. Go ahead and merge.

One quick question: is the link matrix in the function really required? It is used to just create a spmatrix of ones. Could we save some memory by simplifying this?

**Review by cpranav93 — APPROVED** [review]

**Comment by meiertgrootes** [comment]
@cpranav93 @vmgaribay new notebooks with the local attachement implementations : LocalAttach_alt and LocalAttachTensor

**Comment by cpranav93** [comment]
In local attach tensor, the only way to control the number of new edges is through the probability value. This could lead to increasing number of edges every step until we start reaching saturation. Is this the expected behaviour of the model? @vmgaribay @meiertgrootes

**Comment by cpranav93** [comment]
I really like the simplicity of the implementation with the inbuilt functions in the alternative option. Might be good to check how this works in comparison and see if we can use this as the base just to make the code much more understandable.

**Comment by vmgaribay** [comment]
I was under the impression that the link generation and link deletion could be somewhat balanced?

**Comment by meiertgrootes** [comment]
> I was under the impression that the link generation and link deletion could be somewhat balanced?

Not sure what you mean exactly? you can specify the number of links to be created , and /or choose to modulate that by a probability, as in the original PTM code. Isn't it the same for link deletion @cpranav93 ?

**Pull request merged**
