### PR TITLE
Add network metrics

### LINKED ISSUE #70: Track average connectivity of network
With the network evolving over time the average connectivity will also evolve. We would like to trace this explicitly, making it available via the model class. This would allow it to be used for monitoring and feedback.

Possible metrics are
- [ ] mean connectivity. This would be trivial to implement via number of edges and number of nodess/agents
- [ ] modal connectivity. This is more expensive, requiring the actual distribution of node connectivity. If calculated other metrics like skewness etc could also be considered

### PR DESCRIPTION
**Pull request by SarahAlidoost**
closes #70 

see [my comment](https://github.com/SDCCA/DGL-PTM/issues/70#issuecomment-2182904234)

### CODE REVIEW

**Review by vmgaribay — APPROVED** [review]
Looks good. Just a note, if you rename mean_connectivity to average_degree, the meaning will be less ambiguous for network scientists.

**Comment by SarahAlidoost** [comment]
> Looks good. Just a note, if you rename mean_connectivity to average_degree, the meaning will be less ambiguous for network scientists.

Thanks for reviewing, it is renamed now.

**Comment by SarahAlidoost** [comment]
@vanlankveldthijs The broken workflow is fixed [here](https://github.com/SDCCA/DGL-PTM/pull/81/commits/184830b0da623af4c102e7416230dfbebef5ee04), please let me know if we can merge this PR.

**Comment by vanlankveldthijs** [comment]
Implementation looks good.

I think the test(s) could be better.
Currently, it's only testing that the model.average_degree is set. The tests check that the value is the same as the output of the average_degree(...) method, but not that the average_degree(...) method gives the correct output.

If we know that the graph we use for testing is always the same, we could check once what the average degree is and in the test compare to that hard-coded number.
If the testing graph is somehow initialized randomly, we might still be fine there, if the random seed is always the same.

**Review by vanlankveldthijs — COMMENTED** [review]
Implementation looks good.

I think the test(s) could be better.
Currently, it's only testing that the model.average_degree is set. The tests check that the value is the same as the output of the average_degree(...) method, but not that the average_degree(...) method gives the correct output.

If we know that the graph we use for testing is always the same, we could check once what the average degree is and in the test compare to that hard-coded number.
If the testing graph is somehow initialized randomly, we might still be fine there, if the random seed is always the same.

**Pull request merged**
