### PR TITLE
Use pyproject and add github workflow

### LINKED ISSUE #56: Pin version of pydantic in environment file
We are using pydantic version 2. The major version should be mentioned in the environment file.

### LINKED ISSUE #57: Use pyproject.toml and remove environment file
We can move the dependencies to` pyproject.toml` file when everything can be installed by pip.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
closes #57 
closes #56

Todo:
- [ ] add a test for gpu  --> currently github does not run jobs on GPU. see issue #59
- [ ] remove old workflow files from dgl_ptm/.github --> see issue #60

Note:

- If you run `pip install dgl`, pypi does not install the latest dgl but dgl 1.1.3. see [here](https://pypi.org/project/dgl/). However, as seen here, on mac and windows, the latest dgl is installed. In all cases, tests are successful. 
- For running on GPU, I kept the environment file because the cuda version of dgl cannot be installed with pip. I tested the script [gpu_sample_run](https://github.com/SDCCA/DGL-PTM/blob/master/DGL_testing/gpu_sample_run.py) manually on snellius with the environment `dgl_ptm_cuda`.

### CODE REVIEW

**Comment by SarahAlidoost** [comment]
@meiertgrootes and @vanlankveldthijs when you have time, can you please review this PR? thanks.

**Comment by vanlankveldthijs** [comment]
Assuming creating the environment is either a problem with my machine or something that will be fixed, is it possible to run the GPU tests trough pytest?
If not, is the gpu_sample_run test called when github tests the repo, or could this be added?
If that is also not really possible, then there should be a comment somewhere to run this test manually after making changes that could affect running on GPU.

**Comment by SarahAlidoost** [comment]
> Trying to reproduce the GPU tests on my machine made pip fail when trying to create the conda environment (dgl_ptm_cuda).
> 
> Pip subprocess error: ERROR: Ignored the following yanked versions: 1.11.0 ERROR: Ignored the following versions that require a different python version: [...] ERROR: Could not find a version that satisfies the requirement scipy==1.10.1 (from dgl-ptm) [...] ERROR: No matching distribution found for scipy==1.10.1

Thanks for reviewing. I was able to reproduce the error. The issue was that python versions were missing from the environment file. Now it is fixed. Can you please try it again?

**Comment by vanlankveldthijs** [comment]
> > Assuming creating the environment is either a problem with my machine or something that will be fixed, is it possible to run the GPU tests trough pytest? If not, is the gpu_sample_run test called when github tests the repo, or could this be added?
> 
> The test for GPU cannot be run by github because it needs GPU. I have submitted the issue #59.

Nice.

> 
> > If that is also not really possible, then there should be a comment somewhere to run this test manually after making changes that could affect running on GPU.
> 
> Good point, I think it should be added to a contributing document not only on how to run this but also on other tests. Shall I add an issue to update the [CONTRIBUTING.md](https://github.com/SDCCA/DGL-PTM/blob/master/dgl_ptm/CHANGELOG.md)?Or any suggestions on where to add the comment? There is also a [running_dgl_ptm_on_snellius_with_gpu.md](https://github.com/SDCCA/DGL-PTM/blob/master/docs/running_dgl_ptm_on_snellius_with_gpu.md) in doc folder. I also made the issue #60.

CONTRIBUTING.md seems like a good place to add the comment. The running on Snellius doc may not be opened by people using GPU on other systems, but it's probably a good idea to repeat the same comment there, or refer to the contrib doc.

Thanks for adding the issues.

**Comment by vanlankveldthijs** [comment]
> Thanks for reviewing. I was able to reproduce the error. The issue was that python versions were missing from the environment file. Now it is fixed. Can you please try it again?

It not installs without error.

However, activating the environment and trying to run python gpu_sample_run.py gives an error "ImportError: Cannot load Graphbolt C++ library".
I'm assuming this has something to do with my cuda install. I'll see if I can track down the error.

**Comment by meiertgrootes** [comment]
Installation using pure pip works. TestModelRun fails at runtime. The underlying issue is 
`FileNotFoundError: Cannot find DGL C++ sparse library at /Users/eslt0101/mambaforge/envs/tdgl/lib/python3.11/site-packages/dgl/dgl_sparse/libdgl_sparse_pytorch_2.1.1.dylib`

this is a known issue on mac osx (see also #45 ), which seems to require pinning to pytorch 2.0.0

**Comment by fnattino** [comment]
Pip installation seems to work for me (OS X) only on Python 3.11 (not on 3.9 or 3.10).
 
I have built (conda) environments with Python 3.9, 3.10 and 3.11:

```shell
conda create -n py3.X -c conda-forge python=3.X
conda activate py3.X
pip install -e .[dev]
```

Running `pytest` in the three environments:

* Python 3.9.19: `E   ImportError: Cannot load Graphbolt C++ library` 
* Python 3.10.14: `E   ImportError: Cannot load Graphbolt C++ library`
* Python 3.11.9: `6 passed in 8.42s` (**Runs fine**)

Environments (`pip freeze`):
 
<details>
<summary>  Python 3.9 environment </summary> 

```
annotated-types==0.6.0
asciitree==0.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
coverage==7.5.1
dask==2024.5.0
dgl==2.2.0
-e git+ssh://git@github.com/SDCCA/DGL-PTM.git@c89e5e6d5b1ff033b46356fa0ca026f77c0146dd#egg=dgl_ptm&subdirectory=dgl_ptm
exceptiongroup==1.2.1
fasteners==0.19
filelock==3.14.0
fsspec==2024.5.0
idna==3.7
importlib_metadata==7.1.0
iniconfig==2.0.0
Jinja2==3.1.4
locket==1.0.0
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.2.1
numcodecs==0.12.1
numpy==1.26.4
packaging==24.0
pandas==2.2.2
partd==1.4.2
pillow==10.3.0
pluggy==1.5.0
psutil==5.9.8
pycodestyle==2.11.1
pydantic==2.7.1
pydantic_core==2.18.2
pytest==8.2.0
pytest-cov==5.0.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.31.0
ruff==0.4.4
scipy==1.10.1
six==1.16.0
sympy==1.12
tomli==2.0.1
toolz==0.12.1
torch==2.1.1
torchaudio==2.1.1
torchdata==0.7.1
torchvision==0.16.1
tqdm==4.66.4
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
xarray==2024.5.0
zarr==2.18.1
zipp==3.18.2
```
</details>


<details> 
<summary> Python 3.10 environment </summary> 

```
annotated-types==0.6.0
asciitree==0.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
coverage==7.5.1
dask==2024.5.0
dgl==2.2.0
-e git+ssh://git@github.com/SDCCA/DGL-PTM.git@c89e5e6d5b1ff033b46356fa0ca026f77c0146dd#egg=dgl_ptm&subdirectory=dgl_ptm
exceptiongroup==1.2.1
fasteners==0.19
filelock==3.14.0
fsspec==2024.5.0
idna==3.7
importlib_metadata==7.1.0
iniconfig==2.0.0
Jinja2==3.1.4
locket==1.0.0
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.3
numcodecs==0.12.1
numpy==1.26.4
packaging==24.0
pandas==2.2.2
partd==1.4.2
pillow==10.3.0
pluggy==1.5.0
psutil==5.9.8
pycodestyle==2.11.1
pydantic==2.7.1
pydantic_core==2.18.2
pytest==8.2.0
pytest-cov==5.0.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.31.0
ruff==0.4.4
scipy==1.10.1
six==1.16.0
sympy==1.12
tomli==2.0.1
toolz==0.12.1
torch==2.1.1
torchaudio==2.1.1
torchdata==0.7.1
torchvision==0.16.1
tqdm==4.66.4
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
xarray==2024.5.0
zarr==2.18.1
zipp==3.18.2
```
</details>

<details>
<summary> Python 3.11 environment </summary> 

```
annotated-types==0.6.0
asciitree==0.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
coverage==7.5.1
dask==2024.5.0
dgl==2.2.0
-e git+ssh://git@github.com/SDCCA/DGL-PTM.git@c89e5e6d5b1ff033b46356fa0ca026f77c0146dd#egg=dgl_ptm&subdirectory=dgl_ptm
fasteners==0.19
filelock==3.14.0
fsspec==2024.5.0
idna==3.7
importlib_metadata==7.1.0
iniconfig==2.0.0
Jinja2==3.1.4
locket==1.0.0
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.3
numcodecs==0.12.1
numpy==1.26.4
packaging==24.0
pandas==2.2.2
partd==1.4.2
pillow==10.3.0
pluggy==1.5.0
psutil==5.9.8
pycodestyle==2.11.1
pydantic==2.7.1
pydantic_core==2.18.2
pytest==8.2.0
pytest-cov==5.0.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.31.0
ruff==0.4.4
scipy==1.10.1
six==1.16.0
sympy==1.12
toolz==0.12.1
torch==2.1.1
torchaudio==2.1.1
torchdata==0.7.1
torchvision==0.16.1
tqdm==4.66.4
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
xarray==2024.5.0
zarr==2.18.1
zipp==3.18.2
```
</details>

**Comment by meiertgrootes** [comment]
@SarahAlidoost  I Just reran install on a pristine py 3.11.9 environment. It passes as for @fnattino.

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost I Just reran install on a pristine py 3.11.9 environment. It passes as for @fnattino.

@meiertgrootes The default macos runner of github `macos-latest` works with `arm64` where tests pass with different versions of python `[3.9, 3.10, 3.11]`. I created a GitHub action with [the runner `macos-12` with arch `x64`](https://github.com/SDCCA/DGL-PTM/blob/d7cabe37503e91bc628b9b9f435b9dd93b5b15cd/.github/workflows/build_macos_x64.yml) and was able to reproduce the errors that you and @fnattino got, see the test results of [macos x64 on pythons 3.9, 3.10, 3.11](https://github.com/SDCCA/DGL-PTM/actions/runs/9582802424/job/26422593372).  

To fix the issue, I removed the python versions 3.9 and 3.10. All tests are now green with python 3.11. Note that python 3.9 [`end-of-life`](https://devguide.python.org/versions/#supported-versions) will be next year anyway. Please let me know if this is acceptable and if the pull request can be merged.

**Comment by meiertgrootes** [comment]
@SarahAlidoost Thank you. Requiring python >=3.11 is fine.

**Review by meiertgrootes — COMMENTED** [review]
All issues addressed. Agreed to pin python at/above 3.11. Merging on behalf of @SarahAlidoost as discussed 20-06-2024

**Pull request merged**
